version: "3"

services:
  app:
    image: quetzalarc/p100-api-go
    container_name: p100-api
    ports:
      - 3000:3000
    environment:
      - APP_PORT=3000
      - APP_EMAIL=
      - APP_PASSWORD=
      - DEVICE_IP=
      - USER_EMAIL=
      - USER_PASSWORD=

networks:
  default:
    name: p100-api
